
eureka:
  instance:
    prefer-ip-address: true 
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
info:
  app:
    name: application
    description: It is my microservice application
spring:
  config:
    activate:
      on-profile: default
  application:
    name: Config-Default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: MICROSERVICES

