
eureka:
  instance:
    prefer-ip-address: true 
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
info:
  app:
    name: application
    description: It is my microservice application
spring:
  config:
    activate:
      on-profile: default
  application:
    name: Config-Default
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: NAnO!2O23$*m0ng0db!!
      database: NABI
      port: 27017               
      host: 44.242.158.48
